### ISSUE TITLE
JSON error while parsing the All Metadata file

### ISSUE THREAD

**Issue by nlpravi** [google-research-datasets/MAVE#2]
Hi 
I downloaded All_Amazon_Meta.json and when I run clean_amazon_product_metadata_main.sh, I get the error below. Not sure what I'm doing wrong. 

Thank you

Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 1198, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 537, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/Users/ravi.kondadadi@avalara.com/opt/anaconda3/lib/python3.8/site-packages/apache_beam/transforms/core.py", line 1635, in <lambda>
    wrapper = lambda x, *args, **kwargs: [fn(x, *args, **kwargs)]
  File "/Users/ravi.kondadadi@avalara.com/opt/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/ravi.kondadadi@avalara.com/opt/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/ravi.kondadadi@avalara.com/opt/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by liyang2019** [comment]
Hi,

Could you first make sure to install requirements.txt and then ensure the following
1. All_Amazon_Meta.json in the same dir as clean_amazon_product_metadata_main.sh, i.e. "./" when running clean_amazon_product_metadata_main.sh
2. All the labels are kept in the "./labels/" dir.
And try again?

As you can see in clean_amazon_product_metadata_main.sh,  All_Amazon_Meta.json is expected to be outside of "./labels/" and in the same dir as clean_amazon_product_metadata_main.sh.

Thanks!

**Comment by nlpravi** [comment]
Thank you. git clone did not download the jsonl files properly. I had to manually download and copy to the labels folder. It works now. 

Thanks again.

**Comment by liyang2019** [comment]
Thanks for the info.
Another way is to use git lfs (https://git-lfs.github.com/) for downloading those files.
